language: cpp
dist: trusty

matrix:
    include:
        - os: linux
          compiler: gcc
          env:
          addons:
              apt:
                sources:
                    # add PPAs with more up-to-date toolchains
                    - ubuntu-toolchain-r-test
                    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
                packages:
                    # install toolchains
                    - gcc-6
                    - g++-6
                    - cmake
                    - cmake-data

        - os: linux
          compiler: clang
          env:
          addons:
            apt:
                sources:
                     # add PPAs with more up-to-date toolchains
                    - ubuntu-toolchain-r-test
                    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3

            apt:
                packages:
                    - clang-3.7
                    - libiomp-dev
                    - cmake
                    - cmake-data

        - os: osx
          osx_image: xcode8.3
          compiler: clang

before_install:

install:
    - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-6" CC="gcc-6"; fi

notifications:
  email: false

script:
  - $CXX --version
  
  # Install Eigen3
  - hg clone https://bitbucket.org/eigen/eigen/
  - ln -s $HOME/build/vsoftco/qpp/eigen $HOME/eigen
  
  # Build a minimal example
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_INCLUDE_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make
  
  # Build the unit tests
  - cd ../unit_tests
  - mkdir build
  - cd build
  - cmake .. -DEIGEN3_INCLUDE_DIR=$HOME/eigen -DCMAKE_BUILD_TYPE=Debug && make

  # Run the unit tests
  - ./tests/qpp_testing
