language: cpp

env:
  - SH = bash

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    # install toolchains
    - gcc-6
    - g++-6
    - clang++-3.7
    - cmake
    - cmake-data

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - $CXX --version
  - pwd
  - hg clone https://bitbucket.org/eigen/eigen/
  - ln -s $HOME/build/vsoftco/eigen $HOME/eigen
  - cd unit_tests
  - mkdir build
  - cd build
  - cmake .. && make
